build:
    title: OutSystems Support
    input-folder: src
    output-folder: build
    related-title: See Also   
publish:
    url: https://success.outsystems.com/
    root_path: Support
    toc_url: https://success.outsystems.com/
    toc_root_path: Support
    skip_toc_publish: True
    skip_edit_links: False
checktoc:
    url: https://success.outsystems.com/
    root_path: ""
    mindtouch-toc-path: Support/TOC
    auto-toc-path: Documentation/Unlisted/Technical_Communication/Wiki_Tree_Support
